<html>
hhhh
<p><?php $block->sayHello();?></p>

<style>
table {  font-family: arial, sans-serif;  border-collapse: collapse;  width: 100%;  margin-top: 30px;}
td, th {  border: 1px solid #dddddd;  text-align: left;  padding: 8px;  }
tr:nth-child(even) { background-color: #dddddd; }
.post-id{width:2%} .post-name{width:20%} .post-email{width:20%} .post-message{width:40%} .post-category{width:15%}

</style>

<table>
  <tr>
    <th class="post-id">Id</th>
    <th class="post-name">Name</th>
    <th class="post-email">email</th>
    <th class="post-category">category</th>
    <th>message</th>//???
  </tr>
    <?php
    //to show the whole table
        foreach ($block->getPostCollection() as $post){
            echo '<tr>
                    <td>'.$post->getPostId().'</td>
                    <td>'.$post->getName().'</td>
                    <td>'.$post->getEmail().'</td>
                    <td>'.$post->getCategory().'</td>
                    <td>'.$post->getPostMessage().'</td>


                  </tr>';
        }
    ?>
</table>


</html>
